

# Archiving & publishing green data

*Detailed information on [archiving](https://fgb-rdm.nl/rdm/definitions/Definitions.html#archivingdata){target="_blank"} & [publishing](https://fgb-rdm.nl/rdm/definitions/Definitions.html#publishingdata){target="_blank"} data can be found on the [Summary of the FGB Archiving Guidelines page](https://fgb-rdm.nl/rdm/archiving/ArchivingGuidelinesSummary.html){target="_blank"}.*

-   [YODA](https://rdm.vu.nl/topics/yoda.html){target="_blank"} is the default archive for green data
    -   Ensure that you review the [additional security considerations](https://fgb-rdm.nl/rdm/tools/YODAInstructionsFGB.html#protection){target="_blank"} for archiving green data on YODA
    -   Additional guidance for archiving data on YODA, regardless of the risk level is found in the [FGB YODA instructions](https://fgb-rdm.nl/rdm/tools/YODAInstructionsFGB.html#furtherArchiving){target="_blank"}
-   Green data may also be archived in [DataverseNL](https://dataverse.nl/dataverse/FGB){target="_blank"} if YODA is not feasible
-   If neither YODA nor DataverseNL are feasible archives for your data, contact the [faculty data stewards](mailto:research.data.fgb@vu.nl) as soon as possible to discuss this
    -   Although green data are low-risk, they technically fall under the GDPR, which can put restrictions on which external archives may be used. The earlier you discuss the need for an alternative archive with the data stewards the better!

------------------------------------------------------------------------

<br>
