
## Purpose & goal

This tool is intended to provide insight into the privacy and security risks posed by the data you will use in your research. Enter the types of data you will collect, the types of participants you will study, and whether the information or subject matter in the data are sensitive in nature. Based on your input, you will be provided a privacy risk colour-coding and recommendations for keeping the data safe during and after your research.

<em>**NB**: this tool is designed for research that involves human subjects on some level (even indirectly through reuse of public data or through research on materials derived from humans, such as cells or other tissues). If your data have nothing to do with human research subjects in any way (e.g. animal research), you can review the [confidentiality risks table on this page](https://fgb-rdm.nl/Security/PrivacyRisks.html#confidentiality){target="_blank"} to determine which category your data fall into.</em>
<!-- "_ _" seems to not be working here to italicize the above text so using html <em> tags -->

### Technical considerations

When filling in the specific data and participant types, you can start by typing in the input field. If your data/participant type is recognized, you will see an option or options related to what you entered in the field. If not, your data/participant type may still be in the list, but worded differently. The types are listed alphabetically for easier searching. If you still cannot find the data/participant type that applies to your situation, please let us know via the feedback form (found under the *Feedback* tab) or [research.data.fgb@vu.nl](mailto:research.data.fgb@vu.nl){.email}. 

### Data types

Enter all of the specific types of data used in your research that you wish to investigate. You can optionally select one or more of the general types of data to filter the specific data options. The tool will assign a risk of participant/research subject re-identification based on the data types you select. This will appear on the X-axis of the analysis plot once the analysis is complete. More information on [the concept of re-identifiability can be found on this page](https://fgb-rdm.nl/Security/PrivacyRisks.html#reID){target="_blank"}.

You do not have to enter all of the data types you will use in your research if you plan on segregating some of the data at certain stages of your research. For example, if you plan on storing higher-risk data separately from lower-risk data, you can investigate these two groups separately to see what the risks are for the groupings you create. More information is found below in the section on data processing activities.

_**NB**: When selecting data types, focus on what makes the data type unique from other types. In other words, if you select clinical report forms (CRFs), the raw version of these data often include other overlapping data types such as name, age, date of birth and gender. If you will be collecting CRF data will all of those other overlapping data types, then make sure to also select name, age, date of birth and gender in addition to CRF data. If you will be collecting CRF data that has been stripped of this overlapping information, then select only CRF data._

### Participant/research subject types

_**NB**: Participant and research subject is used interchangeably here. You are primarily concerned with the individuals that the data are about. These individuals may indeed be participants in your study, but you could also be collecting data from participants reporting on other people. For example, your participants may be parents reporting information about their children, in which case your research subjects are the children (and potentially also the parents depending on the nature of the data collected). You may also reuse data from existing sources without actively recruiting participants for your study, in which case, your research subjects are the individuals whose data you are reusing._

Enter all of the specific types of participants/research subjects that will be included in your research. You can optionally select adult participants or child participants to filter out the available options. The tool will assign an overall risk level for participant vulnerability based on the highest risk present. This result will appear on the Y-axis of the analysis plot once the analysis is complete. More information on [the concept of participant vulnerability can be found on this page](https://fgb-rdm.nl/Security/PrivacyRisks.html#vulnerability){target="_blank"}.

If only some types of data will be collected with certain participants and you plan on segregating the data from different participant types, then you can opt to enter the combinations that are logical to your plan. For example, if you are collecting different data from your healthy adult participants than you healthy child participants and you want to store these datasets separately, you can enter the data and participant types in the groupings you have in mind. More information is found below in the section on data processing activities.

When selecting participant types, select specific categories only if that information about the participant will be known within the data and the research results. For example, you may have a study of otherwise healthy adults who incidentally include some LGBTQ individuals or people of colour, but if you will not actively collect that information on the participants (and therefore that information will not be represented within the data) then you can select just healthy adults. Of course, use your discretion here: if your study includes questions about sexual preferences or gender identity, it is safer to choose LGBTQ adults as one of your selections.

_**NB**: Some participant types will automatically adjust the input for the data sensitivity section from "No" to "Yes" because of how vulnerable these participants are. You can still select the appropriate sensitivity (see the next section for further information), i.e. even if the participants are very vulnerable, but the information is definitely not sensitive in nature, you can return the input selection to "No"._

### Risk of harm

When contemplating risk of harm, consider whether the information or subject matter that your data represent are about sensitive, taboo, stigmatized or otherwise potentially harmful topics. If the data are [special under the GDPR](https://fgb-rdm.nl/legal/GDPRBasics.html#special){target="_blank"} the risk of harm *may* be elevated, but this is not always the case; if data fall into the "special" data category, use this as a warning sign for elevated risks of harm. The primary rule of thumb is to contemplate whether the information represented in the data add additional risks of harm to the research subjects, in combination with and/or beyond what is already known about their vulnerability. More information on [the risk of harm concept can be found on this page](https://fgb-rdm.nl/Security/PrivacyRisks.html#harm){target="_blank"}.

The default for risk of harm is set to "No", but you can adjust this to "Yes" if the content of your data elevate the risks of harm. For certain research subject populations that belong to highly stigmatized or marginalized groups, the risk of harm will automatically switch to a default of "Yes". In such a case, you can return the risk of harm to "No" if in your estimation the risks posed by the data to the research population are not elevated. You can also discuss this further with the [FGB Privacy Officer](mailto:research.data.fgb@vu.nl) if you are unsure.

### Data processing activities

The default setting for the tool is to account for all possible data processing activities. If all options are selected, you will be given advice based on the risk assessment for all of the possible data processing activities where specific advice on data risks is necessary to help you make choices to protect participants' privacy and ensure security is maintained. However, if you only want recommendations for some data processing activities, for example, if you want to investigate data storage because you want to see what the recommendations will be for certain combinations of data types and participant types, then you can select the data processing activities that you are interesting in and that applies to the data & participant types you've entered into the tool.

### Support

If you have any questions on the tool or you want to offer suggestions (additional data/participant type options or adjustments to the risk assessment results), feel free to contact the REPS team via [research.data.fgb@vu.nl](mailto:research.data.fgb@vu.nl){.email} or fill in the feedback form found under the *Feedback* tab.
