

# Student use of red data

*Detailed information on use of data by students can be found on the [Security for Students page](https://fgb-rdm.nl/Security/SecurityForStudents.html){target="_blank"}. If you will be supervising students who are given access to research data of any risk level, ensure that you have reviewed the general requirements on this page and that your students have read the [Security Basics page](https://fgb-rdm.nl/Security/SecurityBasics.html){target="_blank"}.*

-   If your red data require a custom solution for data storage, make sure to inform the IT specialists helping you that students will also require access to these data, as that will have an impact on how they develop the custom solution
-   If you are already storing your red data on YODA, you can provide access for your student within the YODA environment
    -   Review the storage considerations for red data on the [Security for Students page](https://fgb-rdm.nl/Security/SecurityForStudents.html#storage){target="_blank"} to ensure that your students can safely and securely work with *only* the data they are allowed to access

------------------------------------------------------------------------

<br>
